// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: data.proto
// Protobuf Java Version: 4.27.2

package org.kreps.iotdb.protos;

/**
 * Protobuf type {@code batch.DataResponse}
 */
public final class DataResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:batch.DataResponse)
    DataResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      DataResponse.class.getName());
  }
  // Use DataResponse.newBuilder() to construct.
  private DataResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private DataResponse() {
    points_ = com.google.protobuf.ByteString.EMPTY;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.kreps.iotdb.protos.Data.internal_static_batch_DataResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.kreps.iotdb.protos.Data.internal_static_batch_DataResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.kreps.iotdb.protos.DataResponse.class, org.kreps.iotdb.protos.DataResponse.Builder.class);
  }

  public static final int POINTS_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString points_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes points = 1;</code>
   * @return The points.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPoints() {
    return points_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!points_.isEmpty()) {
      output.writeBytes(1, points_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!points_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, points_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.kreps.iotdb.protos.DataResponse)) {
      return super.equals(obj);
    }
    org.kreps.iotdb.protos.DataResponse other = (org.kreps.iotdb.protos.DataResponse) obj;

    if (!getPoints()
        .equals(other.getPoints())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + POINTS_FIELD_NUMBER;
    hash = (53 * hash) + getPoints().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.kreps.iotdb.protos.DataResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.kreps.iotdb.protos.DataResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.kreps.iotdb.protos.DataResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.kreps.iotdb.protos.DataResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.kreps.iotdb.protos.DataResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.kreps.iotdb.protos.DataResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.kreps.iotdb.protos.DataResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.kreps.iotdb.protos.DataResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.kreps.iotdb.protos.DataResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.kreps.iotdb.protos.DataResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.kreps.iotdb.protos.DataResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.kreps.iotdb.protos.DataResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.kreps.iotdb.protos.DataResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code batch.DataResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:batch.DataResponse)
      org.kreps.iotdb.protos.DataResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.kreps.iotdb.protos.Data.internal_static_batch_DataResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.kreps.iotdb.protos.Data.internal_static_batch_DataResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.kreps.iotdb.protos.DataResponse.class, org.kreps.iotdb.protos.DataResponse.Builder.class);
    }

    // Construct using org.kreps.iotdb.protos.DataResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      points_ = com.google.protobuf.ByteString.EMPTY;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.kreps.iotdb.protos.Data.internal_static_batch_DataResponse_descriptor;
    }

    @java.lang.Override
    public org.kreps.iotdb.protos.DataResponse getDefaultInstanceForType() {
      return org.kreps.iotdb.protos.DataResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.kreps.iotdb.protos.DataResponse build() {
      org.kreps.iotdb.protos.DataResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.kreps.iotdb.protos.DataResponse buildPartial() {
      org.kreps.iotdb.protos.DataResponse result = new org.kreps.iotdb.protos.DataResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.kreps.iotdb.protos.DataResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.points_ = points_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.kreps.iotdb.protos.DataResponse) {
        return mergeFrom((org.kreps.iotdb.protos.DataResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.kreps.iotdb.protos.DataResponse other) {
      if (other == org.kreps.iotdb.protos.DataResponse.getDefaultInstance()) return this;
      if (other.getPoints() != com.google.protobuf.ByteString.EMPTY) {
        setPoints(other.getPoints());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              points_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString points_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes points = 1;</code>
     * @return The points.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPoints() {
      return points_;
    }
    /**
     * <code>bytes points = 1;</code>
     * @param value The points to set.
     * @return This builder for chaining.
     */
    public Builder setPoints(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      points_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bytes points = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPoints() {
      bitField0_ = (bitField0_ & ~0x00000001);
      points_ = getDefaultInstance().getPoints();
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:batch.DataResponse)
  }

  // @@protoc_insertion_point(class_scope:batch.DataResponse)
  private static final org.kreps.iotdb.protos.DataResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.kreps.iotdb.protos.DataResponse();
  }

  public static org.kreps.iotdb.protos.DataResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DataResponse>
      PARSER = new com.google.protobuf.AbstractParser<DataResponse>() {
    @java.lang.Override
    public DataResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DataResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DataResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.kreps.iotdb.protos.DataResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

