// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: data.proto
// Protobuf Java Version: 4.27.2

package org.kreps.iotdb.protos;

public final class Data {
  private Data() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      Data.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_batch_DataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_batch_DataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_batch_DataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_batch_DataResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndata.proto\022\005batch\"F\n\013DataRequest\022\023\n\013me" +
      "asurement\030\001 \001(\t\022\021\n\tstartDate\030\002 \001(\t\022\017\n\007en" +
      "dDate\030\003 \001(\t\"\036\n\014DataResponse\022\016\n\006points\030\001 " +
      "\001(\0142@\n\006Sender\0226\n\007getData\022\022.batch.DataReq" +
      "uest\032\023.batch.DataResponse\"\0000\001B\032\n\026org.kre" +
      "ps.iotdb.protosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_batch_DataRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_batch_DataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_batch_DataRequest_descriptor,
        new java.lang.String[] { "Measurement", "StartDate", "EndDate", });
    internal_static_batch_DataResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_batch_DataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_batch_DataResponse_descriptor,
        new java.lang.String[] { "Points", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
