// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: data.proto
// Protobuf Java Version: 4.27.2

package org.kreps.iotdb.protos;

public interface DataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:batch.DataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes points = 1;</code>
   * @return The points.
   */
  com.google.protobuf.ByteString getPoints();
}
