/**
 * @fileoverview gRPC-Web generated client stub for batch
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.27.2
// source: data.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.batch = require('./data_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.batch.SenderClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.batch.SenderPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.batch.DataRequest,
 *   !proto.batch.DataResponse>}
 */
const methodDescriptor_Sender_getData = new grpc.web.MethodDescriptor(
  '/batch.Sender/getData',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.batch.DataRequest,
  proto.batch.DataResponse,
  /**
   * @param {!proto.batch.DataRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.batch.DataResponse.deserializeBinary
);


/**
 * @param {!proto.batch.DataRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.batch.DataResponse>}
 *     The XHR Node Readable Stream
 */
proto.batch.SenderClient.prototype.getData =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/batch.Sender/getData',
      request,
      metadata || {},
      methodDescriptor_Sender_getData);
};


/**
 * @param {!proto.batch.DataRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.batch.DataResponse>}
 *     The XHR Node Readable Stream
 */
proto.batch.SenderPromiseClient.prototype.getData =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/batch.Sender/getData',
      request,
      metadata || {},
      methodDescriptor_Sender_getData);
};


module.exports = proto.batch;

